### ISSUE TITLE
./configure doesnt check for sodium/.. headers

### ISSUE THREAD

**Issue by FliegendeWurst** [cathugger/mkp224o#10]
Just a small issue, but it actually checks for pcre2 so I thought I would report it

**Comment by cathugger** [comment]
if headers aren't installed it'll break at compile stage with message about missing headers.
checking for that at configure sounds like more effort (I hate current format of configure script) for questionable gain.
pcre2 is checked because it provides convenient tool to query needed CFLAGS and libraries, which allows for more flexibility there.
what would be benefit to check for sodium headers?

**Comment by FliegendeWurst** [comment]
Oh well, I just thought it was a convention to do that.

**Comment by cathugger** [comment]
well, it kind of is, dunno, though in this case it'd just slow down configure script.
most of software which use autotools check for much more of C and posix compliance things (sometimes configure script end up being slower than compilation itself), though I'm not quite seeing the point of that.
will probably add comment about intentionally not checking every required thing.

**Comment by cathugger** [comment]
https://github.com/cathugger/mkp224o/commit/f171063cb033ae464fd8de6e55e64908fdca1d1d
