### ISSUE TITLE
Invalid HS descriptor. Rejected.

### ISSUE THREAD

**Issue by cstest2** [cathugger/mkp224o#12]
When I restart v3 hidden service it does not work immediately. On first start, it works but not on restart. I am using Tor 0.3.3.9.

This seems to be related to Tor bug report https://trac.torproject.org/projects/tor/ticket/27310

My Tor log:

Sep 02 11:21:15.000 [info] upload_descriptor_to_hsdir(): Service [scrubbed] current descriptor of revision 0 initiated upload request to [scrubbed] with index [scrubbed]
Sep 02 11:21:15.000 [info] rep_hist_note_used_internal(): New port prediction added. Will continue predictive circ building for 2227 more seconds.
..........
Sep 02 11:21:16.000 [info] connection_ap_handshake_send_begin(): Sending up to 14185 + 0 bytes of queued-up data
Sep 02 11:21:16.000 [info] connection_edge_process_relay_cell(): -1: end cell (closed normally) for stream 2319. Removing stream.
Sep 02 11:21:16.000 [info] connection_free_minimal(): Freeing linked Socks connection [open] with 0 bytes on inbuf, 0 on outbuf.
Sep 02 11:21:16.000 [info] handle_response_upload_hsdesc(): Uploaded hidden service descriptor (status 400 ("Invalid HS descriptor. Rejected."))
Sep 02 11:21:16.000 [info] handle_response_upload_hsdesc(): Uploading hidden service descriptor: http status 400 ("Invalid HS descriptor. Rejected.") response from dirserver '178.79.163.169:9001'. Malformed hidden service descriptor?

**Comment by cathugger** [comment]
Not sure if it's tor' bug or my thing doing anything wrong (especially since it works on first start).
It should be generating valid key, and, well, other than private ed25519 key, it also makes public key and hostname file for it. I guess you could ensure that public key and hostname files are correct, by removing/renaming them and letting tor regenerate.
There isn't much what could go wrong, other than private key being invalid, but iirc my code checks for that.

**Comment by cathugger** [comment]
(im not really good at remembering ed25519 internals atm, but I think even bad key would sorta work, as in it would produce kinda valid looking public key which shouldn't be rejected)

**Comment by cstest2** [comment]
Tor devs said there "If you moved your HS from 035 to 034, you are likely to hit the revision counter issue because you are using a value that is way too low (most likely around 0 since it had to start from the start)". 

In my above Tor log files there is line "current descriptor of revision 0 initiated upload request". Is "revision 0", probably written inside generated secret_key, correct or should it be something else?

**Comment by cathugger** [comment]
>Is "revision 0", probably written inside generated secret_key, correct or should it be something else?

I don't think it's inside secret key. You can look inside key yourself, secret keys start with `== ed25519v1-secret: type0 ==`, null padding and then binary data which is secret key material. Neither ed25519v1 nor type0 are different in my hidden services, running 0.3.3.9.

Also, that issue is about someone downgrading to 0.3.4.7 from 0.3.5.0, so unsure how that's relevant. When I restart stuff, my services are usually available for me in much less than 3 hours so I don't see it affecting me.

**Comment by cathugger** [comment]
¯\_(ツ)_/¯

**Comment by cathugger** [comment]
from log in linked tor ticket, I'd say it something about your tor setup to blame.
it's full of stuff like `Sep 02 11:21:10.000 [notice] Bootstrapped 0%: Starting` and
```
Sep 02 11:21:10.000 [info] read_file_to_str(): Could not open "/var/lib/tor/data-1/cached-certs": No such file or directory
Sep 02 11:21:10.000 [info] read_file_to_str(): Could not open "/var/lib/tor/data-1/cached-consensus": No such file or directory
Sep 02 11:21:10.000 [info] read_file_to_str(): Could not open "/var/lib/tor/data-1/unverified-consensus": No such file or directory
Sep 02 11:21:10.000 [info] read_file_to_str(): Could not open "/var/lib/tor/data-1/cached-microdesc-consensus": No such file or directory
Sep 02 11:21:10.000 [info] read_file_to_str(): Could not open "/var/lib/tor/data-1/unverified-microdesc-consensus": No such file or directory
Sep 02 11:21:10.000 [info] tor_mmap_file(): Could not open "/var/lib/tor/data-1/cached-microdescs" for mmap(): No such file or directory
Sep 02 11:21:10.000 [info] read_file_to_str(): Could not open "/var/lib/tor/data-1/cached-microdescs.new": No such file or directory
Sep 02 11:21:10.000 [info] microdesc_cache_reload(): Reloaded microdescriptor cache. Found 0 descriptors.
Sep 02 11:21:10.000 [info] tor_mmap_file(): Could not open "/var/lib/tor/data-1/cached-descriptors" for mmap(): No such file or directory
Sep 02 11:21:10.000 [info] tor_mmap_file(): Could not open "/var/lib/tor/data-1/cached-extrainfo" for mmap(): No such file or directory
```
which show that you're starting with state deleted, which means that it can not pick up revision counter properly because it has no access to previous state, thus I guess stuff gets rejected because of it.
From ticket I also noticed that pre-035 versions use something like increment by one revision number scheme, while 035 and up use timestamp (which in this your usage pattern with no state would actually work better I think).
PS: you shouldn't paste such huge logs as messages in bug reports (use file attachments/pastebins for that)

**Comment by cstest2** [comment]
My log is after Tor service full restart, meaning that I delete "/var/lib/tor/data-1" folder and then restart Tor service. That's the reason why there no files in Tor data folder.

After this full Tor restart, v2 hidden service start working within 3-4 mins (tested on another remote system) but v3 hidden services does not start so quickly (it takes several hours to become available).

**Comment by cstest2** [comment]
Anyway I think deleting state file could be the problem. Found some explanations at https://trac.torproject.org/projects/tor/ticket/22940

So it seems that keys are fine and there are no problems with mkp224o or with Tor. Thanks for explanations.

**Comment by cathugger** [comment]
ohyeah, if you're deleting state file then rev counter probably starts ticking from 0, which is what causes rejections.
I guess don't delete state file for now if you do v3 services.
version 0.3.5 should fix it, as from my understanding, it uses timestamp, which doesn't need anything in state file.
