### ISSUE TITLE
[Feature request] To Pause and Resume

### ISSUE THREAD

**Issue by OIVAS7572** [cathugger/mkp224o#59]
To Pause and Resume the sessions (like hashcat)

**Comment by xanoni** [comment]
```bash
pause () {
	if killall -STOP "$1"
	then
		echo "[+] $1 successfully paused!"
	else
		echo "[-] $1 Failed to pause $1"
	fi
}

unpause () {
	if killall -CONT "$1"
	then
		echo "[+] $1 successfully continued!"
	else
		echo "[-] $1 Failed to continue $1"
	fi
}
```

Usage:
```bash
$ pause mkp224o
$ unpause mkp224o
```

**Comment by xanoni** [comment]
(or you just press CTRL+Z ... or CTRL+S / CTRL+Q)

**Comment by xanoni** [comment]
well it's just normal pausing and resuming of processes ... I typically just start `mkp224o` in a `screen` session and then I press CTRL+Z to pause it and enter `fg` to resume it ...

Obviously this doesn't survive a system restart .... for that there would have to be functionality to persist state on disk

**Comment by xanoni** [comment]
Does someone understand the algorithm and can tell whether persisting sessions actually adds value?

Maybe a restart is not much worse given we initialize with a new seed every time.

**Comment by scribblemaniac** [comment]
Pausing and resuming is mostly useless. Every time the program restarts, it will use a new seed.The only exception to this is if you use the `-p`/`-P` argument to set a fixed seed. In that case, restarting the program with the same passphrase will run through all the keys generated previously before generating new keys. I've made a PR that adds optional checkpointing support for passphrase-based generation here: #61. When you use this, it will skip over practically all the previously tested keys upon restarting the program.

Note: Generally you shouldn't use the passphrase option because of the limited entropy of passphrases. And to reiterate, if you don't use passphrases then you do not need to make checkpoints and the -c flag will do nothing.

**Comment by xanoni** [comment]
That's what I assumed. Great.

**Comment by xanoni** [comment]
After superficially scanning the code I also noticed that the seed is automatically getting initialized with random data, so you're right ... I didn't see this documented, so to be safe I wrote a bash script that initializes the program with a /dev/random seed ... unnecessarily, but better safe than sorry ...

https://github.com/cathugger/mkp224o/blob/fc6285523f615e31f9d313a667e6ca8a9d781872/worker_fast.inc.h#L40

https://github.com/cathugger/mkp224o/blob/fc6285523f615e31f9d313a667e6ca8a9d781872/worker_slow.inc.h#L33

https://github.com/cathugger/mkp224o/blob/fc6285523f615e31f9d313a667e6ca8a9d781872/worker_batch.inc.h#L43

https://github.com/cathugger/mkp224o/blob/fc6285523f615e31f9d313a667e6ca8a9d781872/ed25519/ed25519.h#L167

**Comment by scribblemaniac** [comment]
> so to be safe I wrote a bash script that initializes the program with a /dev/random seed ... unnecessarily, but better safe than sorry ...

If you're suggesting that you're passing the data from /dev/random as a passphrase, that is not a good idea for multiple reasons. First, if you do not match or exceed the seed size, your initial seed will have less entropy. Second, when you do not specify a passphrase, the generator will be reseeded randomly occasionally. If you specify a passphrase, the generator will increment the seed instead. This is convenient because it makes the behavior deterministic, but it is worse from a security perspective, especially if you may want to use more than one of the generated results.

**Comment by xanoni** [comment]
What I was trying to say is simply that I was originally not aware that the seed was auto-generated/refreshed, because to my knowledge that is not documented anywhere.

**Comment by cathugger** [comment]
mkp224o do full refresh of per-thread state when given thread successfully finds a match. this is so that leaking of any single key generated by same mkp224o would have zero chances of impacting security of other keys generated on the same run. passphrase mode is designed to be deterministic and thus keys of the same run aren't protected the same way. i still try to use hash so leak of later keys wont impact security of earlier keys but there is no protection of the opposite so this mode of operation is strictly less secure in this way.
