### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by GarfieldsPipe** [cathugger/mkp224o#71]
The latest version (v1.5.0) is almost 2 years old. I think a new official release including Windows build could benefit from 2 years of improvements.

**Comment by cathugger** [comment]
may happen soon-ish

**Comment by cathugger** [comment]
was thinking of releasing something like v2.0.0 with multiple crypto/filter implementations bundled together & selectable at runtime, but that's kinda hard to finish, & im not even sure how filter selectivity would work.
one of reasons i haven't been releasing more often is because i sorta lost windows bin building scripts due to drive failure (thanks to not putting them in git repo).
so yeah idk may just do v1.6.0 & think about v2 later.

have a nice picture meanwhile
![95775083_p0](https://user-images.githubusercontent.com/26472432/168348301-066c43d2-e05d-44a3-9e43-af61b746a3d7.png)

**Comment by cathugger** [comment]
done https://github.com/cathugger/mkp224o/releases/tag/v1.6.0

**Comment by cathugger** [comment]
i ended up re-tagging because fixed some annoying warning spam i shouldnt have left in & win64 x amd64 routines, hopefully that won't trip anything/anyone up
